### ISSUE TITLE
Doesn't work with ActiveRecord relations

### ISSUE THREAD

**Issue by TrevorHinesley** [chaps-io/access-granted#23]
For instance

```ruby
@artists = Artist.all
authorize! :read, @artists
```

Will not work, no matter if `can :read, Artist` is specified in the policy. This does work:

```ruby
@artists = Artist.all
authorize! :read, Artist
```

But is insufficient for obvious reasons. Each one needs to be checked individually to make sure this collection is viable for this user in this case.

Also, something like this seems like it may work:

```ruby
@artists = Artist.all
authorize! :read, @artists.first
```

But if `@artists.first == nil` in this case of an empty collection, this will result in access denied.

**Comment by pokonski** [comment]
It is not intended to work with relations because they are a different class than `Artist`. If you just want to check if user has a general permission to read Artists just use a class as the second argument:

```
authorize! :read, Artist
@artists = Artist.all
```

Not sure what your aim is here, but generally looping through every artist and filtering it in the controller is a terrible practice. If you know what Artists belong to the user just filter them instead of doing `all`.

**Comment by TrevorHinesley** [comment]
They're being filtered, I think the best option here would be to do the
.first alternative that I mentioned, but if it's an empty collection let it
pass or allow conditions for that empty case? Just a thought.

**Comment by ambethia** [comment]
@TrevorHinesley [Rolify](https://github.com/RolifyCommunity/rolify) handles what I think you're trying to do.
