### ISSUE TITLE
errors with non-logged in users

### ISSUE THREAD

**Issue by vince** [chaps-io/access-granted#32]
I've got a configure block defined in a pretty standard way:

```
    role :admin, proc { |user| user.is_admin } do
       can :manage, Post
    end
```

When I view the page as a non logged in user though I get an error:

> undefined method `is_admin' for nil:NilClass

I must be missing something pretty simple -- unless it depends on authentication before authorization?  Little help please?

**Comment by pokonski** [comment]
This of course expected since current_user is not present. This is something you have to take outside of Access Granted.

A popular pattern for solving this is always returning *some* user. For example, if you use Devise, do this in your application controller:

```def current_user
super || User.new
end
```

this will make sure there's always an instance of a User you can run checks on.

**Comment by vince** [comment]
Perfect, thanks for the clarification and quick response!

**Comment by pokonski** [comment]
Glad I could help :+1:

On 14 July 2016 at 16:34, Vince Wadhwani <notifications@github.com> wrote:

> Perfect, thanks for the clarification and quick response!
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/chaps-io/access-granted/issues/32#issuecomment-232683317>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAIQ6rqEM2Br-O6RqhgtZ6WbtFuvnc-Rks5qVkjcgaJpZM4JL-0A>
> .
>



-- 
Piotr Okoński
piotrek@okonski.org | +48 792 097 151
